<p style="text-align:center">
    <img src="https://media.licdn.com/dms/image/v2/D560BAQGRKQWaOldXvg/company-logo_200_200/company-logo_200_200/0/1723551442229/cambo_ai_logo?e=2147483647&v=beta&t=FrK5k676UJMjoOULl4R3euChg1VvClew28fxNscSd9E" width="80" alt="CamboAI Logo">
</p>

# **I. Objectives**

**Estimated time needed: 60 minutes**

**After completing this lab you will be able to:**
- Know the fundamentals of the ETL (Extract, Transform, Load) process using Python and PostgreSQL.
- ETL is a crucial method in data engineering, allowing you to gather data from various sources, clean and transform it, and then load it into a database for analysis and reporting.

- You will start by reading data from a CSV file using the Pandas library.
- This data may contain inconsistencies or errors, so you will perform several transformation and cleaning steps,
    1. Handling missing values
    2. Rmoving duplicates
    3. Ensuring the data types are correct
    

- Once your data is clean and transformed, you will load it into a PostgreSQL database.
- This step involves establishing a connection to the database and using SQL commands to insert the data into a designated table.

- By the end of this lab, you will have gained practical experience in data manipulation and will understand how to effectively prepare data for storage in a relational database.

**Let's get started!**

# **II. Import Libraries**

In [ ]:
# import pandas libraries
import pandas as pd
import numpy as np

# ignore warning
import warnings
warnings.filterwarnings('ignore')

# **III. Read Dataset**

In [ ]:
# read dataset from sales_transaction_dataset.csv
df = pd.read_csv('../dataset/sales_transaction_dataset.csv')

# **IV. Exploratory Data Analysis (EDA)**

In [ ]:
# show top 5 records
df.head()

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country
0,581482,12.09.19,22485,Set Of 2 Wooden Market Crates,21.47,12,17490.0,United Kingdom
1,581475,12.09.19,22596,Christmas Star Wish List Chalkboard,10.65,36,13069.0,United Kingdom
2,581475,12.09.19,23235,Storage Tin Vintage Leaf,11.53,12,13069.0,United Kingdom
3,581475,12.09.19,23272,Tree T-Light Holder Willie Winkie,10.65,12,13069.0,United Kingdom
4,581475,12.09.19,23239,Set Of 4 Knick Knack Tins Poppies,11.94,6,13069.0,United Kingdom

In [ ]:
# show buttom 5 records
df.tail()

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country
536345,C536548,12.01.18,22168,Organiser Wood Antique White,18.96,-2,12472.0,Germany
536346,C536548,12.01.18,21218,Red Spotty Biscuit Tin,14.09,-3,12472.0,Germany
536347,C536548,12.01.18,20957,Porcelain Hanging Bell Small,11.74,-1,12472.0,Germany
536348,C536548,12.01.18,22580,Advent Calendar Gingham Sack,16.35,-4,12472.0,Germany
536349,C536548,12.01.18,22767,Triple Photo Frame Cornice,20.45,-2,12472.0,Germany

In [ ]:
# show random 5 sample
df.sample(5)

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country
15180,580692,12.05.19,17107D,Flower Fairy 5 Drawer Liners,7.24,5,13173.0,United Kingdom
193424,567333,9/19/2019,23199,Jumbo Bag Apples,6.19,10,14282.0,United Kingdom
222681,564825,8/30/2019,85099F,Jumbo Bag Strawberry,7.24,1,14825.0,United Kingdom
357350,552493,05.09.19,84912A,Pink Rose Washbag,13.62,1,17493.0,United Kingdom
411808,547063,3/20/2019,85187,S/12 Mini Rabbit Easter,11.94,1,14769.0,United Kingdom

In [ ]:
# check number of row and column
df.shape

(536350, 8)

In [ ]:
# check column name
df.columns

Index(['TransactionNo', 'Date', 'ProductNo', 'ProductName', 'Price',
       'Quantity', 'CustomerNo', 'Country'],
      dtype='object')

In [ ]:
# check data type of each column
df.dtypes

TransactionNo     object
Date              object
ProductNo         object
ProductName       object
Price            float64
Quantity           int64
CustomerNo       float64
Country           object
dtype: object

In [ ]:
# check null value in all records
df.isnull().sum()

TransactionNo     0
Date              0
ProductNo         0
ProductName       0
Price             0
Quantity          0
CustomerNo       55
Country           0
dtype: int64

In [ ]:
# check info of all records
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 536350 entries, 0 to 536349
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   TransactionNo  536350 non-null  object
 1   Date           536350 non-null  object
 2   ProductNo      536350 non-null  object
 3   ProductName    536350 non-null  object
 4   Price          536350 non-null  float64
 5   Quantity       536350 non-null  int64
 6   CustomerNo     536295 non-null  float64
 7   Country        536350 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 32.7+ MB

# **V. Data Cleaning**

## A). Clean TransactionNo column

In [ ]:
# find records with null value in "TransactionNo"
df[df['TransactionNo'].isnull()]

Empty DataFrame
Columns: [TransactionNo, Date, ProductNo, ProductName, Price, Quantity, CustomerNo, Country]
Index: []

In [ ]:
# drop all records in "TransactionNo" that have null value
df = df.dropna(subset=['TransactionNo'], inplace=False)

In [ ]:
# find records with null value after removed null
df[df['TransactionNo'].isnull()]

Empty DataFrame
Columns: [TransactionNo, Date, ProductNo, ProductName, Price, Quantity, CustomerNo, Country]
Index: []

## B). Clean CustomerNo column

In [ ]:
# find records with null value in "CustomerNo"
df[df['CustomerNo'].isnull()].head()

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country
6511,C581406,12.08.19,46000M,Polyester Filler Pad 45x45cm,6.19,-240,NaN,United Kingdom
6512,C581406,12.08.19,46000S,Polyester Filler Pad 40x40cm,6.19,-300,NaN,United Kingdom
90098,C575153,11.08.19,22947,Wooden Advent Calendar Red,44.25,-1,NaN,United Kingdom
102671,C574288,11.03.19,22178,Victorian Glass Hanging T-Light,25.37,-1,NaN,United Kingdom
117263,C573180,10/28/2019,23048,Set Of 10 Lanterns Fairy Light Star,14.50,-1,NaN,United Kingdom

In [ ]:
# drop all the records with "CustomerNo" have null value
df = df.dropna(subset=['CustomerNo'], inplace=False)

In [ ]:
# convert "CustomerNo" from float to int
df['CustomerNo'] = df['CustomerNo'].astype(int)

In [ ]:
# convert "CustomerNo" from integer to string
df['CustomerNo'] = df['CustomerNo'].astype(str)

In [ ]:
# find records with null value after removed null
df[df['CustomerNo'].isnull()].head()

Empty DataFrame
Columns: [TransactionNo, Date, ProductNo, ProductName, Price, Quantity, CustomerNo, Country]
Index: []

In [ ]:
# check null value after removed
df.isnull().sum()

TransactionNo    0
Date             0
ProductNo        0
ProductName      0
Price            0
Quantity         0
CustomerNo       0
Country          0
dtype: int64

## C). Clean Date column

In [ ]:
# find unique tuype of Date
# df['Date'].unique()

# convert "Date" using the first format - m.d.y
date_format_1 = pd.to_datetime(df['Date'], format='%m.%d.%y', errors='coerce')

# convert "Date" using the second format - m/d/Y
date_format_2 = pd.to_datetime(df['Date'], format='%m/%d/%Y', errors='coerce')

# combine both results
stardardized_date = date_format_1.fillna(date_format_2)

# create new column to replace existing "Date"
df['stardardized_date'] = stardardized_date

In [ ]:
df.head()

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country,stardardized_date
0,581482,12.09.19,22485,Set Of 2 Wooden Market Crates,21.47,12,17490,United Kingdom,2019-12-09
1,581475,12.09.19,22596,Christmas Star Wish List Chalkboard,10.65,36,13069,United Kingdom,2019-12-09
2,581475,12.09.19,23235,Storage Tin Vintage Leaf,11.53,12,13069,United Kingdom,2019-12-09
3,581475,12.09.19,23272,Tree T-Light Holder Willie Winkie,10.65,12,13069,United Kingdom,2019-12-09
4,581475,12.09.19,23239,Set Of 4 Knick Knack Tins Poppies,11.94,6,13069,United Kingdom,2019-12-09

## D). Clean Quantity column

In [ ]:
# convert datatype from integer to string
df['Quantity'] = df['Quantity'].astype(str)

# find records of "Quantity" that contain (-)
df[df['Quantity'].str.contains('-', case=False)].head()

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country,stardardized_date
1616,C581484,12.09.19,23843,Paper Craft Little Birdie,6.19,-80995,16446,United Kingdom,2019-12-09
1617,C581490,12.09.19,22178,Victorian Glass Hanging T-Light,6.19,-12,14397,United Kingdom,2019-12-09
1618,C581490,12.09.19,23144,Zinc T-Light Holder Stars Small,6.04,-11,14397,United Kingdom,2019-12-09
1619,C581568,12.09.19,21258,Victorian Sewing Box Large,6.19,-5,15311,United Kingdom,2019-12-09
1620,C581569,12.09.19,84978,Hanging Heart Jar T-Light Holder,6.19,-1,17315,United Kingdom,2019-12-09

In [ ]:
# remove (-) from number in "Quantity"
df['Quantity'] = df['Quantity'].str.replace('-', '', regex=False)

In [ ]:
# find records of "Quantity" that contain (-) after removed
df[df['Quantity'].str.contains('-', case=False)].head()

Empty DataFrame
Columns: [TransactionNo, Date, ProductNo, ProductName, Price, Quantity, CustomerNo, Country, stardardized_date]
Index: []

In [ ]:
# convert "Quantity" from string to float
df['Quantity'] = df['Quantity'].astype(float)

## E). Remove Duplicate records

In [ ]:
# find rows that are identical across all columns
duplicates = df[df.duplicated(keep=False)]

# add a flag column to mark which ones are duplicates
df['is_duplicate'] = df.duplicated(keep=False)

# show only the duplicate rows
duplicate_rows = df[df['is_duplicate'] == True]
duplicate_rows.head()

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country,stardardized_date,is_duplicate
984,581497,12.09.19,21481,Fawn Blue Hot Water Bottle,7.24,1.0,17497,United Kingdom,2019-12-09,True
985,581497,12.09.19,21481,Fawn Blue Hot Water Bottle,7.24,1.0,17497,United Kingdom,2019-12-09,True
1350,581538,12.09.19,22992,Revolver Wooden Ruler,6.19,1.0,14446,United Kingdom,2019-12-09,True
1354,581538,12.09.19,22694,Wicker Star,6.19,1.0,14446,United Kingdom,2019-12-09,True
1356,581538,12.09.19,23275,Set Of 3 Hanging Owls Ollie Beak,6.19,1.0,14446,United Kingdom,2019-12-09,True

In [ ]:
# find duplicated records by "TransactionNo" and "ProductNo"
df[(df['TransactionNo'] == '581497') & (df['ProductNo'] == '21481')]

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country,stardardized_date,is_duplicate
984,581497,12.09.19,21481,Fawn Blue Hot Water Bottle,7.24,1.0,17497,United Kingdom,2019-12-09,True
985,581497,12.09.19,21481,Fawn Blue Hot Water Bottle,7.24,1.0,17497,United Kingdom,2019-12-09,True

In [ ]:
# remove all identical rows (keep only the first occurrence)
df = df.drop_duplicates()

In [ ]:
# check duplicate rows in the entire dataset after removed
df[(df['TransactionNo'] == '581497') & (df['ProductNo'] == '21481')]

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country,stardardized_date,is_duplicate
984,581497,12.09.19,21481,Fawn Blue Hot Water Bottle,7.24,1.0,17497,United Kingdom,2019-12-09,True

In [ ]:
# show all data after removed
df.head()

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country,stardardized_date,is_duplicate
0,581482,12.09.19,22485,Set Of 2 Wooden Market Crates,21.47,12.0,17490,United Kingdom,2019-12-09,False
1,581475,12.09.19,22596,Christmas Star Wish List Chalkboard,10.65,36.0,13069,United Kingdom,2019-12-09,False
2,581475,12.09.19,23235,Storage Tin Vintage Leaf,11.53,12.0,13069,United Kingdom,2019-12-09,False
3,581475,12.09.19,23272,Tree T-Light Holder Willie Winkie,10.65,12.0,13069,United Kingdom,2019-12-09,False
4,581475,12.09.19,23239,Set Of 4 Knick Knack Tins Poppies,11.94,6.0,13069,United Kingdom,2019-12-09,False

In [ ]:
# drop "Date" column
df = df.drop('Date', axis=1)

In [ ]:
# rename a "Standardized_date"
df = df.rename(columns={'stardardized_date': 'Date'})

In [ ]:
df.head()

,TransactionNo,ProductNo,ProductName,Price,Quantity,CustomerNo,Country,Date,is_duplicate
0,581482,22485,Set Of 2 Wooden Market Crates,21.47,12.0,17490,United Kingdom,2019-12-09,False
1,581475,22596,Christmas Star Wish List Chalkboard,10.65,36.0,13069,United Kingdom,2019-12-09,False
2,581475,23235,Storage Tin Vintage Leaf,11.53,12.0,13069,United Kingdom,2019-12-09,False
3,581475,23272,Tree T-Light Holder Willie Winkie,10.65,12.0,13069,United Kingdom,2019-12-09,False
4,581475,23239,Set Of 4 Knick Knack Tins Poppies,11.94,6.0,13069,United Kingdom,2019-12-09,False

In [ ]:
# reorder columns using reindex
df = df.reindex(columns=['CustomerNo', 'Date', 'TransactionNo', 'ProductNo', 'ProductName', 'Quantity', 'Price', 'Country'])

In [ ]:
# convert the all column names to lowercase
df.columns = df.columns.str.lower()

In [ ]:
# check datatype after converted
df.dtypes

customerno               object
date             datetime64[ns]
transactionno            object
productno                object
productname              object
quantity                float64
price                   float64
country                  object
dtype: object

In [ ]:
# check records after cleaned
df.head()

,customerno,date,transactionno,productno,productname,quantity,price,country
0,17490,2019-12-09,581482,22485,Set Of 2 Wooden Market Crates,12.0,21.47,United Kingdom
1,13069,2019-12-09,581475,22596,Christmas Star Wish List Chalkboard,36.0,10.65,United Kingdom
2,13069,2019-12-09,581475,23235,Storage Tin Vintage Leaf,12.0,11.53,United Kingdom
3,13069,2019-12-09,581475,23272,Tree T-Light Holder Willie Winkie,12.0,10.65,United Kingdom
4,13069,2019-12-09,581475,23239,Set Of 4 Knick Knack Tins Poppies,6.0,11.94,United Kingdom

# **VI. Write the Cleaned Data into file (CSV or Excel)**

In [ ]:
# save cleaned data as a csv file
df.to_csv('../results/sales_transaction_dataset_cleaned.csv', index=False)

In [ ]:
# save cleaned data as a excel file
with pd.ExcelWriter('../results/sales_transaction_dataset_cleaned.xlsx') as writer:
    df.to_excel(writer, sheet_name="sales_transaction", index=False)

# **VII. Write the Cleaned Data into Postgres database**

**1. Install Libraries**

In [ ]:
%pip install sqlalchemy --quiet
%pip install psycopg2 --quiet

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.

**2. Import Libraries**

In [ ]:
# import libraries
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

**3. Creat Connection to PostgreSQL**

- **Syntax:** engine = create_engine(f'postgresql+psycopg2://{username}:{password}@{host}:{port}/{dbname}')

In [ ]:
# credentials
host = "localhost"
dbname = "postgres"
username = "postgres"
password = "post@123!"

# URL-encode password
encoded_password = quote_plus(password)

# build connection URL
db_url = f"postgresql+psycopg2://{username}:{encoded_password}@{host}/{dbname}?sslmode=disable"

# create engine
engine = create_engine(db_url)

# test connection
try:
    with engine.connect() as conn:
        result = conn.execute(text("SELECT NOW();"))
        for row in result:
            print("Connection successful, current time:", row[0])
except Exception as e:
    print("Connection failed:", e)

Connection successful, current time: 2025-10-18 07:03:22.224926+07:00

**4. Create Table in PostgreSQL**

In [ ]:
from sqlalchemy import text

# create table in PostgreSQL using raw SQL
create_table_query = """
CREATE TABLE IF NOT EXISTS tbl_sales_transaction (
    CustomerNo INT NOT NULL,
    Date DATE NOT NULL,
    TransactionNo VARCHAR(50) NOT NULL,
    ProductNo VARCHAR(50) NOT NULL,
    ProductName VARCHAR(255) NOT NULL,
    Quantity INT NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    Country VARCHAR(100) NOT NULL,
    PRIMARY KEY (CustomerNo, ProductNo, Date, TransactionNo)
);
"""

# execute the create table statement
with engine.connect() as connection:
    connection.execute(text(create_table_query))  # wrap SQL in text()
    connection.commit()  # commit the transaction
    print("Table created successfully.")

Table created successfully.

**5. Truncat Table before Load**

In [ ]:
# delete_table_query = """
#     delete from tbl_sales_transaction;
# """
# # Execute the create table statement
# with engine.connect() as connection:
#     connection.execute(text(delete_table_query))  # Wrap SQL in text()
#     connection.commit()
#     print("Truncate Table successfully.")

**6. Load Cleaned Data to Table**

In [ ]:
# load the cleaned data into the table
df.to_sql('tbl_sales_transaction', engine, if_exists='append', index=False)
print("Data loaded successfully.")

Data loaded successfully.

# Excellent! You have just completed this Notebook.

This notebook was created by [Chanthan DINA](https://www.linkedin.com/in/chanthandina/). I hope you found this lab interesting and educational. Feel free to contact me if you have any questions!

## <h3 align="center"> &#169; CamboAI. All rights reserved. <h3/>